using System;
using System.Windows.Forms;
using System.Drawing;
using System.Drawing.Drawing2D;

class ShapedForm : Form
{
  
  public ShapedForm()
  {
    GraphicsPath ellipsePath = new GraphicsPath();
    ellipsePath.AddEllipse(2, 22, 300, 100);
    this.Region = new Region(ellipsePath);
    this.Size = new Size(324, 124);
    this.MouseDown += new MouseEventHandler(ShapedForm_MouseDown);
  }
  
  [STAThreadAttribute]
  public static void Main(String [] Args)
  {
    Application.Run(new ShapedForm());
  }
  
  // Allows dragging the form from anywhere, because the title bar
  // will almost certainly be absent. Hacked and converted this
  // code to C#, from code generated by VB Shaped Form Creator
  // ( http://www.comports.com/AlexVVBSFC.html )
  protected void ShapedForm_MouseDown(object sender, MouseEventArgs e)
  {
    Message m;
    m = Message.Create(this.Handle, 0xa1, new IntPtr(2), new IntPtr(0));
    this.Capture = false;
    this.WndProc(ref m);
  }
}  